### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by A-M-D-R-3-W** [AlexeyLepov/CTkThemesPack#1]
Great themes! Really like Coffee, been using it quite a bit. I noticed there isn't a license and can't find a way to contact you directly, would you mind if I used these for a small open-source app I'm building that will be published here? I'll attribute your repo. Thanks🍻

**Comment by a13xe** [comment]
Absolutely! Feel free to use my themes with any app. Glad you find it useful! 🍻
