### ISSUE TITLE
I love this pack so much! When will there be more themes?

### ISSUE THREAD

**Issue by khaki-git** [AlexeyLepov/CTkThemesPack#2]
I personally hate making CTk Themes myself, choosing hex-codes is a pain in the ass.
I like all of the themes in this pack in it's own way, but I don't think there's enough variety/uniqueness.
Basically, I wish for there to be more themes for me to pick from for my app.

**Comment by a13xe** [comment]
Ty for the feedback!)
Got your request and be adding more themes soon

**Comment by a13xe** [comment]
Hey again! 
I forgot to mention that I added a few new themes yesterday. 
Also, check out this guy's repo, he's got some really cool-looking themes:
https://github.com/rigvedmaanas/CustomTkinterThemes
